FROM python:3.13-slim-bullseye

ARG CLOUDFLARE_EMAIL \
CLOUDFLARE_API_KEY \
CLOUDFLARE_DOMAINS

ENV CLOUDFLARE_EMAIL=$CLOUDFLARE_EMAIL \
CLOUDFLARE_API_KEY=$CLOUDFLARE_API_KEY \ 
CLOUDFLARE_DOMAINS=$CLOUDFLARE_DOMAINS

WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["python", "app.py"]
